### ISSUE TITLE
right side is a little buggy. 

### ISSUE THREAD

**Issue by cgarcia2595** [marc-andrew/off-canvas-infinity-push#2]
Hi I have to say your plugin nav is amazing! I'm having some issues with the right side when I close the menu the wrapper does not fully go back to its original position. The left side is working well and I didn't find no issue, but I want to use the menu in the right side. 

![screen shot 2015-06-02 at 3 01 33 am](https://cloud.githubusercontent.com/assets/8705519/7931206/37d2ea4c-08d4-11e5-99db-ea1de37bef63.png) "the menu is close" 

Any suggestions? 

Thank you

**Comment by marc-andrew** [comment]
Hi,

it is working on the Template. Can you please give more details. What browser & version are you testing?
Can you upload it on http://jsfiddle.net ?
thanks

**Comment by cgarcia2595** [comment]
Well the issue is that it creates a horizontal scroll bar and the even though I have overflow-x: hidden in the body tag as you specified for some reason it still shows the bar in the right side only. I'm using chrome (desktop) and safari in my iphone 5S to check my progress. 

When you swipe your finger to the right in safari or if you drag your cursor to the right after you close the menu in chrome, the wrapper stays in the same location it doesn't go back like it should. 
 
![photo jun 02 3 54 09 am](https://cloud.githubusercontent.com/assets/8705519/7932494/39f4778c-08de-11e5-8bd5-9d9493c711f6.png)

Does it help?

**Comment by marc-andrew** [comment]
Hi,

I believe I replicated the issue. I can see it here on the template: http://www.marcandrew.net/off-canvas-infinity-push/index2.html

when you scroll to the right direction you will see the navigation? Is that the issue you have?

try:

html {
overflow-x: hidden;
}

body {
position: relative;
overflow-x: hidden;
}

**Comment by cgarcia2595** [comment]
Your solution solved the problem, thank you very much.
