### ISSUE TITLE
datepicker in menu closes sidebar

### ISSUE THREAD

**Issue by wim-mertens** [marc-andrew/off-canvas-infinity-push#4]
I have a foundation datepicker in my menu. Problem is, when I select a date the sidebar closes, because the actual calendar gets rendered at the end of <body>. I do like to keep the clicking outside the sidebar feature to close it, but how do I keep it open when clicking on the calendar?

**Comment by marc-andrew** [comment]
Hi @wim-mertens ,

can you please provide more information? Maybe a live code example or screen shot?

Thanks,
Marc

**Comment by wim-mertens** [comment]
Hi Marc,

I think I figured it out already. Can't really show you the link as it's not live yet, but I will see if I can upload a sample of the code soon. Basically, apart from the navigation, I am adding a date picker (foundation 6), inside the sidebar. The calendar gets added dynamically just before the </body> tag so when clicking on the calendar the sidebar closes. Changing your code where it has a function to close the sidebar when clicking anywhere in the body to a specific div solved it. Maybe add an option to avoid clicking body to close, if that makes sense?
